### ISSUE TITLE
Implement ArithmeticSequenceValidator

### ISSUE THREAD

**Issue by schwobaseggl** [Blueshoe/django-secure-passwords#1]
## Missing Implementation

Implement the [`is_arithemtic_sequence`][0] method to return `True` if the passed list of integers contains a sequence (123, 5678, 4321, etc.) of length `self.n` or more.

[0]: https://github.com/Blueshoe/django-secure-passwords/blob/9550c452531b0f7dbb4be4cc181d69f2a10aac33/securepasswords/validators.py#L61

**Comment by saurabhlanjewar** [comment]
mplement the is_arithemtic_sequence method
